# Generated by Django 5.1.5 on 2025-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя ученика')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия ученика')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='Введите свой номер телефона')),
                ('messages', models.CharField(blank=True, max_length=200, null=True, verbose_name='Что вас интересует')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя и фамилия учителя')),
                ('name_tk', models.CharField(max_length=250, null=True, verbose_name='Имя и фамилия учителя')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Имя и фамилия учителя')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Имя и фамилия учителя')),
                ('experience', models.IntegerField(verbose_name='Стаж учителя')),
                ('items', models.CharField(max_length=250, verbose_name='Предмет')),
                ('items_tk', models.CharField(max_length=250, null=True, verbose_name='Предмет')),
                ('items_en', models.CharField(max_length=250, null=True, verbose_name='Предмет')),
                ('items_ru', models.CharField(max_length=250, null=True, verbose_name='Предмет')),
                ('teacher_images', models.FileField(upload_to='media/videos/photos/', verbose_name='Фото учителя')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='VideoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_tk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_tk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('video_file', models.FileField(upload_to='media/videos/', verbose_name='Видео')),
                ('image', models.FileField(upload_to='media/videos/photos/', verbose_name='Титульный лист')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
