# Generated by Django 5.1.5 on 2025-01-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eserSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250, verbose_name='Название направлений')),
                ('category_tk', models.CharField(max_length=250, null=True, verbose_name='Название направлений')),
                ('category_en', models.CharField(max_length=250, null=True, verbose_name='Название направлений')),
                ('category_ru', models.CharField(max_length=250, null=True, verbose_name='Название направлений')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
