# Generated by Django 5.1.5 on 2025-01-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eserSite', '0002_cours_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=250, verbose_name='Название курса')),
                ('course_title_tk', models.CharField(max_length=250, null=True, verbose_name='Название курса')),
                ('course_title_en', models.CharField(max_length=250, null=True, verbose_name='Название курса')),
                ('course_title_ru', models.CharField(max_length=250, null=True, verbose_name='Название курса')),
                ('course_description', models.CharField(max_length=250, verbose_name='Описание курса')),
                ('course_description_tk', models.CharField(max_length=250, null=True, verbose_name='Описание курса')),
                ('course_description_en', models.CharField(max_length=250, null=True, verbose_name='Описание курса')),
                ('course_description_ru', models.CharField(max_length=250, null=True, verbose_name='Описание курса')),
                ('course_images', models.FileField(upload_to='media/videos/photos/', verbose_name='Изображение курса')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eserSite.cours_category', verbose_name='Категория курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
