# Generated by Django 5.1.5 on 2025-01-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eserSite', '0003_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours_category',
            options={'verbose_name': 'Категория курсов', 'verbose_name_plural': 'Категории курсов'},
        ),
    ]
