# Generated by Django 5.1.5 on 2025-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eserSite', '0004_alter_cours_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies_title', models.CharField(max_length=250, verbose_name='Название вакансии')),
                ('vacancies_title_tk', models.CharField(max_length=250, null=True, verbose_name='Название вакансии')),
                ('vacancies_title_en', models.CharField(max_length=250, null=True, verbose_name='Название вакансии')),
                ('vacancies_title_ru', models.CharField(max_length=250, null=True, verbose_name='Название вакансии')),
                ('vacancies_experience', models.CharField(max_length=250, verbose_name='Стаж сотрудника')),
                ('vacancies_experience_tk', models.CharField(max_length=250, null=True, verbose_name='Стаж сотрудника')),
                ('vacancies_experience_en', models.CharField(max_length=250, null=True, verbose_name='Стаж сотрудника')),
                ('vacancies_experience_ru', models.CharField(max_length=250, null=True, verbose_name='Стаж сотрудника')),
                ('vacancies_requirements', models.CharField(max_length=250, verbose_name='Требования к сотруднику')),
                ('vacancies_requirements_tk', models.CharField(max_length=250, null=True, verbose_name='Требования к сотруднику')),
                ('vacancies_requirements_en', models.CharField(max_length=250, null=True, verbose_name='Требования к сотруднику')),
                ('vacancies_requirements_ru', models.CharField(max_length=250, null=True, verbose_name='Требования к сотруднику')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
