# Generated by Django 5.1.5 on 2025-02-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eserSite', '0005_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сomment_description', models.CharField(max_length=250, verbose_name='Комментарий')),
                ('comment_name', models.CharField(max_length=250, verbose_name='Имя коментатора')),
                ('comment_avtor', models.CharField(max_length=250, verbose_name='Кто написал комментарий')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
